spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    database: postgresql
    show-sql: true
  liquibase:
    change-log: classpath:/db/changelog/db-init.yaml
    enabled: true
    default-schema: hw4
server:
  servlet:
    context-path: "/user-product-app"
